//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jenkins.Notifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jenkins.Notifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeton API.
        /// </summary>
        public static string ApiToken {
            get {
                return ResourceManager.GetString("ApiToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour ecran login.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masquer la fenêtre.
        /// </summary>
        public static string HideWindow {
            get {
                return ResourceManager.GetString("HideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-clique pour afficher la fenêtre, clique droit pour afficher le menu.
        /// </summary>
        public static string IconToolTip {
            get {
                return ResourceManager.GetString("IconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;accès à l&apos;API Jenkins.
        /// </summary>
        public static string JenkinsServiceError {
            get {
                return ResourceManager.GetString("JenkinsServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string JobColumn {
            get {
                return ResourceManager.GetString("JobColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernier rafraichissment.
        /// </summary>
        public static string LastRefreshTime {
            get {
                return ResourceManager.GetString("LastRefreshTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement en cours.
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraîchir.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraichissement (seconde).
        /// </summary>
        public static string RefreshDelay {
            get {
                return ResourceManager.GetString("RefreshDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL fichier de configuration distant.
        /// </summary>
        public static string RemotePath {
            get {
                return ResourceManager.GetString("RemotePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la sauvegarde des paramètres.
        /// </summary>
        public static string SaveSettingsError {
            get {
                return ResourceManager.GetString("SaveSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la fenêtre.
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Serveur Jenkins.
        /// </summary>
        public static string UrlServerJenkins {
            get {
                return ResourceManager.GetString("UrlServerJenkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue.
        /// </summary>
        public static string ViewColumn {
            get {
                return ResourceManager.GetString("ViewColumn", resourceCulture);
            }
        }
    }
}
